---
language: go

sudo: false

env:
 - PACKAGE=consul
 - PACKAGE=consul-cli
 - PACKAGE=consul-template
 - PACKAGE=consul-ui
 - PACKAGE=distributive
 - PACKAGE=distributive-calico
 - PACKAGE=distributive-chronos
 - PACKAGE=distributive-collectd
 - PACKAGE=distributive-collectd-docker
 - PACKAGE=distributive-collectd-marathon
 - PACKAGE=distributive-collectd-zookeeper
 - PACKAGE=distributive-common
 - PACKAGE=distributive-consul
 - PACKAGE=distributive-consul-template
 - PACKAGE=distributive-dnsmasq
 - PACKAGE=distributive-docker
 - PACKAGE=distributive-etcd
 - PACKAGE=distributive-haproxy
 - PACKAGE=distributive-logrotate
 - PACKAGE=distributive-logstash
 - PACKAGE=distributive-mantlui
 - PACKAGE=distributive-marathon
 - PACKAGE=distributive-mesos
 - PACKAGE=distributive-vault
 - PACKAGE=distributive-zookeeper
 - PACKAGE=docker-cleanup
 - PACKAGE=generate-certificate
 - PACKAGE=mantl-dns
 - PACKAGE=nomad
 - PACKAGE=traefik
 - PACKAGE=vault
 - PACKAGE=vault-mantl

addons:
  apt:
    packages:
      # hammer
      - rpm

cache:
  apt: true
  directories:
    - tools

before_install: ./scripts/evaluate-build.sh

# TODO: cache fpm
install:
  - mkdir -p tools/bin || true
  - >
    'which hammer || (go get -v github.com/asteris-llc/hammer
    &&  go build -o tools/bin/hammer github.com/asteris-llc/hammer)'
  - gem install fpm

script:
  - mkdir /tmp/out
  - PATH=tools/bin:$PATH hammer build --output=/tmp/out --stream-logs-for=$PACKAGE $PACKAGE

after_failure: tail logs/*

deploy:
  provider: script
  script: /bin/bash scripts/bintray.sh /tmp/out
  on:
    branch: master
